require "lib/board"
require "lib/row"

describe("Board", function()

  local board

  context("create", function()
    it("can be created", function()
      board = Board.create({})
      assert_not_equal(board, nil)
    end)

    it("sets the cells to nil if no value(s) provided", function()
      board = Board.create()
      assert_not_equal(board.cells, nil)
    end)

    it("accepts board cells values", function()
      board = Board.create({'x', 'o', 'x'})
      assert_not_equal(board.cells, nil)
      assert_equal(board.cells[1], 'x')
      assert_equal(board.cells[2], 'o')
      assert_equal(board.cells[3], 'x')
    end)
  end)

  context("get", function()
    it("retrieves a cell value by index", function()
      board = Board.create({'x', 'o', 'x'})
      assert_equal(board:get(1), 'x')
      assert_equal(board:get(2), 'o')
      assert_equal(board:get(3), 'x')
    end)
  end)

  context("set", function()
    it("sets a cell value by index", function()
      board = Board.create()
      assert_equal(board:get(1), nil)
      board:set(1, 'x')
      assert_equal(board:get(1), 'x')
    end)
  end)

  context("clear", function()
    it("clears a cell value by index", function()
      board = Board.create()
      assert_equal(board:get(1), nil)
      board:set(1, 'x')
      assert_equal(board:get(1), 'x')
      board:clear(1)
      assert_equal(board:get(1), nil)
    end)
  end)

  context("rows", function()
    it("returns a collection of rows", function()
      board = Board.create({1, 2, 3, 4, 5, 6, 7, 8, 9})
      rows = board:rows()
      assert_equal(rows[1], Row.create({1, 2, 3}))
      assert_equal(rows[2], Row.create({4, 5, 6}))
      assert_equal(rows[3], Row.create({7, 8, 9}))
    end)
  end)
end)
